version: 0.0.{build}
environment:
  GITHUB_ACCESS_TOKEN:
    secure: EQWmbklZx2BXtd3MhdqHmC4BKqRabNNV+JmeMvOMbTSkNCRwZ0xm7qfdsvHt+yTz
configuration: Release
platform: Any CPU
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
before_build:
- nuget restore Saucy.sln
build:
  project: Saucy.sln
  verbosity: normal
after_build:
- .\packages\ilmerge.2.14.1208\tools\ilmerge.exe /allowDup /wildcards /out:saucy.exe src\Saucy\bin\Release\Saucy.exe src\Saucy\bin\Release\*.dll
- nuget pack Saucy.nuspec -Version "%APPVEYOR_BUILD_VERSION%" -Properties "Configuration=Release;Platform=AnyCPU"
artifacts:
- path: Saucy.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
  artifact: /.*\.nupkg/