version: 0.0.{build}
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- git config --global core.autocrlf false
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
before_build:
- nuget restore Saucy.sln
build:
  project: Saucy.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
artifacts:
- path: Saucy.nupkg
- path: ConsoleOut.log
- path: ConsoleError.log
deploy:
- provider: NuGet
  api_key:
    secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
  artifact: /.*\.nupkg/