version: 0.0.{build}
skip_tags: true
init:
- git config --global core.autocrlf input
clone_depth: 1
environment:
  GITHUB_ACCESS_TOKEN:
    secure: EQWmbklZx2BXtd3MhdqHmC4BKqRabNNV+JmeMvOMbTSkNCRwZ0xm7qfdsvHt+yTz
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
before_build:
- nuget restore Saucy.sln
- .\packages\saucy.0.0.60\tools\saucy.exe restore
build:
  project: Saucy.sln
  verbosity: normal
after_build:
- .\packages\ilmerge.2.14.1208\tools\ilmerge.exe /allowDup /wildcards /out:saucy.exe src\Saucy\bin\Release\Saucy.exe src\Saucy\bin\Release\*.dll
- nuget pack Saucy.nuspec -Version "%APPVEYOR_BUILD_VERSION%" -Properties "Configuration=Release;Platform=AnyCPU"
artifacts:
- path: Saucy.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
  artifact: /.*\.nupkg/
on_success:
- git config --global credential.helper store
- git config --global user.email "andrew@epworth-consulting.co.uk"
- git config --global user.name "Andrew Craven"
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
- git tag build-%APPVEYOR_BUILD_VERSION%
- git push origin --tags